name: Test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        pytorch-version: ["1.11.0", "1.12.1", "1.13.1", "2.0.0"]
      max-parallel: 4
    env:
      OS: 'ubuntu-latest'
      PYTHON: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies with PyTorch ${{ matrix.pytorch-version }}
      run: |
          conda install pytorch==${{ matrix.pytorch-version }}